[package]
name = "ascon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
pretty_env_logger = "0.5"

[dev-dependencies]
rand = "0.8"
